const PDFDocument = require("pdfkit");

/**
 * Generate a certification "certificate" PDF on the fly for a user +
 * completed certification. Returns a Buffer (caller streams/sends it).
 */
function generateCertificatePdf({ userName, certificationName, issuer, earnedDate, level }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", layout: "landscape", margin: 50 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;

    // Border
    doc
      .lineWidth(3)
      .strokeColor("#2563eb")
      .rect(24, 24, pageWidth - 48, pageHeight - 48)
      .stroke();
    doc
      .lineWidth(1)
      .strokeColor("#94a3b8")
      .rect(36, 36, pageWidth - 72, pageHeight - 72)
      .stroke();

    doc
      .fillColor("#0f172a")
      .fontSize(12)
      .font("Helvetica")
      .text("SKILLPATH AI  ·  SOPRA STERIA", 0, 70, { align: "center" });

    doc
      .fillColor("#2563eb")
      .fontSize(32)
      .font("Helvetica-Bold")
      .text("Certificate of Achievement", 0, 110, { align: "center" });

    doc
      .fillColor("#334155")
      .fontSize(14)
      .font("Helvetica")
      .text("This certifies that", 0, 175, { align: "center" });

    doc
      .fillColor("#0f172a")
      .fontSize(26)
      .font("Helvetica-Bold")
      .text(userName, 0, 200, { align: "center" });

    doc
      .fillColor("#334155")
      .fontSize(14)
      .font("Helvetica")
      .text("has successfully earned the certification", 0, 245, { align: "center" });

    doc
      .fillColor("#0d9488")
      .fontSize(22)
      .font("Helvetica-Bold")
      .text(certificationName, 0, 270, { align: "center" });

    doc
      .fillColor("#475569")
      .fontSize(12)
      .font("Helvetica")
      .text(`Issued by ${issuer}  ·  Level: ${level}`, 0, 305, { align: "center" });

    doc
      .fillColor("#475569")
      .fontSize(12)
      .text(`Earned on ${earnedDate}`, 0, 325, { align: "center" });

    doc
      .fillColor("#94a3b8")
      .fontSize(9)
      .text(
        "Generated by LevelUp — SkillPath AI (interim demo data, not an official Microsoft credential document).",
        0,
        pageHeight - 70,
        { align: "center" }
      );

    doc.end();
  });
}

module.exports = { generateCertificatePdf };
